ex: ex_compile.c
	gcc -Wall `pkg-config --cflags glib-2.0` ex_compile.c `pkg-config --libs glib-2.0` -o ex_compile.out
wordcount: word_count.c
	gcc -Wall `pkg-config --cflags glib-2.0` word_count.c `pkg-config --libs glib-2.0` -o word_count.out